on:
    workflow_dispatch:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

name: release-please

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  release-type: node
                  config-file: .release-please-config.json

            - uses: actions/checkout@v4
              if: ${{ steps.release.outputs.release_created }}

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
              if: ${{ steps.release.outputs.release_created }}

            - run: bun install --frozen-lockfile
              if: ${{ steps.release.outputs.release_created }}

            - run: bun test
              if: ${{ steps.release.outputs.release_created }}

            - run: bun run build
              if: ${{ steps.release.outputs.release_created }}

            - uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{ secrets.NPM_TOKEN }}
              if: ${{ steps.release.outputs.release_created }}
